### ISSUE TITLE
OpenRefine - project.vt and index.vt not found

### ISSUE THREAD

**Issue by psychemedia** [psychemedia/sandstorm-apps#1]
In the OpenRefine app, the dev version runs okay to create a project, but when trying to "Create Project" using the packaged app on sandcats, the following error is raised:

```
HTTP ERROR 404

Problem accessing /project. Reason:

    NOT_FOUND
```

OpenRefine log:

```
14:49:25.361 [                   refine] POST /command/core/create-importing-job (14615ms)
14:49:26.366 [                   refine] POST /command/core/importing-controller (1005ms)
14:49:26.683 [                   refine] POST /command/core/get-importing-job-status (317ms)
14:49:27.358 [                   refine] POST /command/core/importing-controller (675ms)
14:49:28.056 [                   refine] POST /command/core/importing-controller (698ms)
14:49:28.108 [              RecordModel] KeyedGroup Column::Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,Column 11,Column 12,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22,Column 23, (52ms)
14:49:28.115 [              RecordModel] KeyedGroup Column::Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,Column 11,Column 12,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22,Column 23, (7ms)
14:49:28.427 [                   refine] POST /command/core/get-models (312ms)
14:49:28.747 [                   refine] POST /command/core/get-rows (320ms)
14:49:29.916 [                   refine] POST /command/core/importing-controller (1169ms)
14:49:29.990 [              RecordModel] KeyedGroup Column::Column 2,Column 3,Column 4,Column 5,Column 6,Column 7,Column 8,Column 9,Column 10,Column 11,Column 12,Column 13,Column 14,Column 15,Column 16,Column 17,Column 18,Column 19,Column 20,Column 21,Column 22,Column 23, (74ms)
14:49:31.237 [                   refine] POST /command/core/get-importing-job-status (1247ms)
14:49:31.575 [                   refine] POST /command/core/cancel-importing-job (338ms)
14:49:32.604 [                 velocity] ResourceManager : unable to find resource 'project.vt' in any resource loader. (1029ms)
...
```

In the dev app, a project is created, but trying to go back to the app frontpage/file listing gives another vt error:

```
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:476)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at org.mozilla.javascript.gen.c6._c6(file:/opt/app/openrefine-2.6-rc.2/webapp/modules/core/MOD-INF/controller.js:633)
    at org.mozilla.javascript.gen.c6._c5(file:/opt/app/openrefine-2.6-rc.2/webapp/modules/core/MOD-INF/controller.js:626)
    at org.mozilla.javascript.gen.c6.call(file:/opt/app/openrefine-2.6-rc.2/webapp/modules/core/MOD-INF/controller.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c6.call(file:/opt/app/openrefine-2.6-rc.2/webapp/modules/core/MOD-INF/controller.js)
    at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.process(ButterflyModuleImpl.java:399)
    at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.run(ButterflyModuleImpl.java:377)
    at org.mozilla.javascript.Context.call(Context.java:515)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:507)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.processScript(ButterflyModuleImpl.java:650)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.process(ButterflyModuleImpl.java:427)
    at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:516)
    at com.google.refine.RefineServlet.service(RefineServlet.java:200)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
    at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
15:11:26.177 [                 velocity] ResourceManager : unable to find resource 'index.vt' in any resource loader. (1ms)
```

**Comment by psychemedia** [comment]
Adding JAVA_HOME to PATH fixes the Velocity package detection issue.

However, whilst it seems that running on a local dev server allows the projects to be saved within the grain, running the packaged app on sandcats doesn't save projects (although you can create new ones and run them ok...)?

**Comment by psychemedia** [comment]
Hmm.. seems to be working now... I can see saved projects; cache problem on the page maybe?
